name: Restrict PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  restrict-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Verify branch names
        id: verify
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"

          # Replace these with your desired branch name patterns
          BASE_PATTERN="^main$"
          HEAD_PATTERN="^release/.*$"

          if [[ ! "$BASE_BRANCH" =~ $BASE_PATTERN ]]; then
            echo "Error: Base branch name '$BASE_BRANCH' does not match pattern '$BASE_PATTERN'."
            exit 1
          fi

          if [[ ! "$HEAD_BRANCH" =~ $HEAD_PATTERN ]]; then
            echo "Error: Head branch name '$HEAD_BRANCH' does not match pattern '$HEAD_PATTERN'."
            exit 1
          fi

      - name: Success message
        run: echo "Branch names are valid. Proceed with the PR."
