name: Restrict PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_target:
    types: [edited]

jobs:
  restrict-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Display pull request information
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"

      - name: Verify allow only release to be merged on main
        id: verify
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"

          BASE_PATTERN="^main$"
          HEAD_PATTERN="^release/.*$"

          if [[ "$BASE_BRANCH" =~ $BASE_PATTERN ]]; then
            if [[ ! "$HEAD_BRANCH" =~ $HEAD_PATTERN ]]; then
              echo "Error: You can't merge '$HEAD_BRANCH' into '$BASE_BRANCH' -> does not match pattern '$HEAD_PATTERN'."
              exit 1
            fi
          fi

      - name: Success message
        run: echo "Branch names are valid. Proceed with the PR."
